spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: orcl
    password: orcl
    driver-class-name: org.h2.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
